name: "Test coverage"

on:
  workflow_run:
    workflows: [node-unit-tests, browser-unit-tests, browser-e2e-tests]
    types:
      - completed

jobs:
  collect-coverage:
    runs-on: ubuntu-latest
    needs:
      [
        node-unit-tests.status,
        node-e2e-tests.status,
        browser-unit-tests.status,
        browser-e2e-tests.status,
      ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

      - name: Log all downloaded artifacts
        run: ls -R
