name: "Node unit tests"

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  node-unit-tests:
    # only run this job if the base branch is dp/testing-groups
    if: github.ref == 'dp/testing-groups'
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: CI Setup
        uses: ./.github/actions/ci-setup

      - name: Build
        run: |
          BUILD_VERSION="0.0.0-${{ github.ref_name }}-$(git rev-parse --short $GITHUB_SHA)" pnpm build

      - name: Node unit tests
        run: pnpm test -- --group=node/unit --group=common/unit --coverage

      - name: Upload coverage to Github artifacts
        uses: actions/upload-artifact@v2
        with:
          name: node-unit-coverage
          path: coverage
