name: Test - Browser

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-browser:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: CI Setup
        uses: ./.github/actions/ci-setup

      - name: Build
        run: pnpm build

      - name: Run Browser Tests
        run: pnpm ci:test-browser

      - name: Upload Browser Coverage
        uses: actions/upload-artifact@v2
        with:
          name: browser
          path: coverage/environments/browser
