name: "Test"

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: CI Setup
        uses: ./.github/actions/ci-setup

      - name: Forc Format Check
        run: pnpm forc:check

      - name: Build
        run: |
          pnpm build

      - name: Lint
        run: |
          pnpm lint

      - name: Checking PR Number
        uses: jwalton/gh-find-current-pr@v1
        id: findPr

      - name: Run tests
        run: |
          pnpm ci:test -- --coverage --bail

      #   uses: ArtiomTr/jest-coverage-report-action@v2
      #   if: ${{ steps.findPr.outputs.number }}
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     package-manager: pnpm
      #     annotations: failed-tests
      #     test-script: pnpm ci:test
      #     prnumber: ${{ steps.findPr.outputs.number }}

      # - name: Run tests no coverage  publishing
      #   if: ${{ !steps.findPr.outputs.number }}
      #   run: |
      #     pnpm ci:test
