name: "Test"

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    uses: FuelLabs/github-actions/.github/workflows/vp-docs.yml@master
    with:
      doc-folder-path: "apps/docs/src"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Working Branch
        uses: actions/checkout@v3

      - name: CI Setup
        uses: ./.github/actions/ci-setup

      - name: Forc Format Check
        run: pnpm forc:check

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Find PR Number
        uses: jwalton/gh-find-current-pr@v1
        id: findPr

      - name: Run tests and collect coverage
        run: pnpm ci:test && pnpm ci:test --browser && pnpm test:merge-coverage && pnpm test:report-coverage

      - name: Upload coverage to Github artifacts
        uses: actions/upload-artifact@v3
        # if: ${{ !steps.findPr.outputs.number }}
        # if: ${{ steps.findPr.outputs.number }}
        with:
          name: coverage-reports
          path: coverage/report

      - name: Download coverage artifact
        uses: dawidd6/action-download-artifact@v2
        if: ${{ steps.findPr.outputs.number }}
        with:
          workflow: test.yaml
          branch: master
          name: coverage-reports
          path: coverage-reports

      - name: Report coverage
        uses: romeovs/lcov-reporter-action@v0.3.1
        if: ${{ steps.findPr.outputs.number }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: coverage/report/lcov.info
          base-lcov-file: coverage-reports/lcov.info
          delete-old-comments: true
          filter-changed-file: true
          title: "Coverage Report"
