name: "Test"

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    uses: FuelLabs/github-actions/.github/workflows/vp-docs.yml@master
    with:
      doc-folder-path: "apps/docs/src"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: CI Setup
        uses: ./.github/actions/ci-setup

      - name: Forc Format Check
        run: pnpm forc:check

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Validate tests
        run: pnpm test:validate

      - name: Find PR Number
        uses: jwalton/gh-find-current-pr@v1
        id: findPr

      - name: Run tests and collect coverage
        run: pnpm ci:test-node && pnpm ci:test-browser && pnpm test:merge-coverage && pnpm test:report-coverage

      - name: Upload coverage to Github artifacts
        uses: actions/upload-artifact@v3
        if: ${{ !steps.findPr.outputs.number }}
        with:
          name: coverage-master
          path: coverage/report

      - name: Download coverage artifact
        uses: dawidd6/action-download-artifact@v2
        # TODO: Remove PR != check once #1182 has been merged
        if: ${{ (steps.findPr.outputs.number) && (steps.findPr.outputs.number != 1182)}}
        with:
          workflow: test.yaml
          branch: master
          name: coverage-master
          path: coverage-master

      # TODO: Delete once #1182 has been merged
      - name: Download coverage artifact (temporary)
        uses: dawidd6/action-download-artifact@v2
        if: ${{ (steps.findPr.outputs.number) && (steps.findPr.outputs.number == 1182)}}
        with:
          workflow: test.yaml
          run_id: 5940564903
          name: coverage-master
          path: coverage-master

      - name: Report coverage
        uses: romeovs/lcov-reporter-action@v0.3.1
        if: ${{ steps.findPr.outputs.number }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: coverage/report/lcov.info
          lcov-base: coverage-master/lcov.info
          delete-old-comments: true
          title: "Coverage Report"
