name: "Test"

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    uses: FuelLabs/github-actions/.github/workflows/vp-docs.yml@master
    with:
      doc-folder-path: "apps/docs/src"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: CI Setup
        uses: ./.github/actions/ci-setup

      - name: Forc Format Check
        run: pnpm forc:check

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Validate tests
        run: pnpm test:validate

  test-node:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: CI Setup
        uses: ./.github/actions/ci-setup

      - name: Build
        run: pnpm build

      - name: Run Node Tests
        run: pnpm ci:test-node

      - name: Upload Node Coverage
        uses: actions/upload-artifact@v2
        with:
          name: node
          path: coverage/environments/node

  test-browser:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: CI Setup
        uses: ./.github/actions/ci-setup

      - name: Build
        run: pnpm build

      - name: Run Browser Tests
        run: pnpm ci:test-browser

      - name: Upload Browser Coverage
        uses: actions/upload-artifact@v2
        with:
          name: browser
          path: coverage/environments/browser

  test:
    runs-on: ubuntu-latest
    needs: [test-node, test-browser]
    steps:
      - name: Generate Coverage Directory
        run: mkdir -p coverage/environments

      - name: Download Coverage for Browser Tests
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: test-browser.yaml
          name: browser
          path: coverage/environments

      - name: Download Coverage for Node Tests
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: test-node.yaml
          name: node
          path: coverage/environments

      - name: Merge Coverage
        run: pnpm test:merge-coverage && pnpm test:report-coverage

      - name: Find PR Number
        uses: jwalton/gh-find-current-pr@v1
        id: findPr

      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v3
        if: ${{ !steps.findPr.outputs.number }}
        with:
          name: coverage-master
          path: coverage/report

      - name: Download Coverage Artifact
        uses: dawidd6/action-download-artifact@v2
        # TODO: Remove PR != check once #1182 has been merged
        if: ${{ (steps.findPr.outputs.number) && (steps.findPr.outputs.number != 1182)}}
        with:
          workflow: test.yaml
          branch: master
          name: coverage-master
          path: coverage-master

      # TODO: Delete once #1182 has been merged
      - name: Download coverage artifact (temporary)
        uses: dawidd6/action-download-artifact@v2
        if: ${{ (steps.findPr.outputs.number) && (steps.findPr.outputs.number == 1182)}}
        with:
          workflow: test.yaml
          run_id: 5940564903
          name: coverage-master
          path: coverage-master

      - name: Report Coverage
        uses: romeovs/lcov-reporter-action@v0.3.1
        if: ${{ steps.findPr.outputs.number }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: coverage/report/lcov.info
          lcov-base: coverage-master/lcov.info
          delete-old-comments: true
          title: "Coverage Report"
