name: "Test"

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    uses: FuelLabs/github-actions/.github/workflows/vp-docs.yml@master
    with:
      doc-folder-path: "apps/docs/src"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: CI Setup
        uses: ./.github/actions/ci-setup

      - name: Forc Format Check
        run: pnpm forc:check

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Find PR Number
        uses: jwalton/gh-find-current-pr@v1
        id: findPr

      - name: Validate Tests
        run: pnpm test:validate

      - name: Run node tests
        run: pnpm ci:test

      - name: Run browser tests
        run: pnpm ci:test --browser

      - name: Generate coverage
        run: pnpm test:report-coverage

      - name: Upload master coverage artifact
        uses: actions/upload-artifact@v3
        if: ${{ !steps.findPr.outputs.number }}
        with:
          name: coverage-reports
          path: ./coverage/coverage-final.json

      - name: Download master coverage artifact
        uses: dawidd6/action-download-artifact@v2
        if: ${{ steps.findPr.outputs.number }}
        with:
          workflow: test.yaml
          branch: master
          name: coverage-reports
          path: coverage-reports

      - name: Post coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2
        if: ${{ steps.findPr.outputs.number }} && ${{steps.findPr.outputs.number != 1182}}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: pnpm
          annotations: failed-tests
          prnumber: ${{ steps.findPr.outputs.number }}
          coverage-file: ./coverage/coverage-final.json
          base-coverage-file: coverage-reports/coverage-final.json

      - name: Post coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2
        if: ${{ steps.findPr.outputs.number }} && ${{steps.findPr.outputs.number == 1182}}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: pnpm
          annotations: failed-tests
          prnumber: ${{ steps.findPr.outputs.number }}
          coverage-file: ./coverage/coverage-final.json
          base-coverage-file: coverage-reports/report.master.json
